/** @type {import('next').NextConfig} */

// scripts/render-pdf.mjs is run via child_process (see lib/pdf.js), not
// imported — Vercel's automatic file tracing only follows real import/
// require statements, so without this the script and its dependencies get
// silently pruned from the deployed function, and it 500s in production
// with "Cannot find package X" (happened twice: once for the whole script,
// once for a single missed transitive dependency, is-url).
//
// react-pdf pulls in ~50 small packages scattered outside its own scope, so
// rather than guess (again), this list was generated by actually tracing
// scripts/render-pdf.mjs with @vercel/nft — the same tool Next uses
// internally — and extracting every node_modules package it touched.
const PDF_DEPENDENCIES = [
  "./scripts/render-pdf.mjs",
  "./node_modules/@babel/runtime/**",
  "./node_modules/@react-pdf/fns/**",
  "./node_modules/@react-pdf/font/**",
  "./node_modules/@react-pdf/image/**",
  "./node_modules/@react-pdf/layout/**",
  "./node_modules/@react-pdf/pdfkit/**",
  "./node_modules/@react-pdf/png-js/**",
  "./node_modules/@react-pdf/primitives/**",
  "./node_modules/@react-pdf/render/**",
  "./node_modules/@react-pdf/renderer/**",
  "./node_modules/@react-pdf/stylesheet/**",
  "./node_modules/@react-pdf/textkit/**",
  "./node_modules/@swc/helpers/**",
  "./node_modules/abs-svg-path/**",
  "./node_modules/base64-js/**",
  "./node_modules/bidi-js/**",
  "./node_modules/brotli/**",
  "./node_modules/clone/**",
  "./node_modules/color-name/**",
  "./node_modules/color-string/**",
  "./node_modules/cross-fetch/**",
  "./node_modules/crypto-js/**",
  "./node_modules/dfa/**",
  "./node_modules/emoji-regex/**",
  "./node_modules/fast-deep-equal/**",
  "./node_modules/fontkit/**",
  "./node_modules/hsl-to-hex/**",
  "./node_modules/hsl-to-rgb-for-reals/**",
  "./node_modules/hyphen/**",
  "./node_modules/is-arrayish/**",
  "./node_modules/is-url/**",
  "./node_modules/jay-peg/**",
  "./node_modules/media-engine/**",
  "./node_modules/node-fetch/**",
  "./node_modules/normalize-svg-path/**",
  "./node_modules/object-assign/**",
  "./node_modules/parse-svg-path/**",
  "./node_modules/postcss-value-parser/**",
  "./node_modules/react/**",
  "./node_modules/restructure/**",
  "./node_modules/simple-swizzle/**",
  "./node_modules/svg-arc-to-cubic-bezier/**",
  "./node_modules/tiny-inflate/**",
  "./node_modules/tr46/**",
  "./node_modules/tslib/**",
  "./node_modules/unicode-properties/**",
  "./node_modules/unicode-trie/**",
  "./node_modules/webidl-conversions/**",
  "./node_modules/whatwg-url/**",
  "./node_modules/yoga-layout/**",
];

const nextConfig = {
  outputFileTracingIncludes: {
    "/api/download": PDF_DEPENDENCIES,
    "/success": PDF_DEPENDENCIES,
  },
};

module.exports = nextConfig;
