import { Resend } from "resend";

// Server-only, same rule as lib/stripe.js — never import from a client component.
const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

// resend.dev works instantly with no setup, for testing only — it can only send
// to the email address you signed up to Resend with. Once ramsforge.co.uk's DNS
// is verified in Resend, change this to something like "RAMS Forge <noreply@ramsforge.co.uk>".
const FROM_ADDRESS = process.env.RESEND_FROM || "RAMS Forge <onboarding@resend.dev>";

export async function sendRamsEmail({ to, trade, pdfBuffer }) {
  if (!resend) {
    console.warn("RESEND_API_KEY not set — skipping email send.");
    return { skipped: true };
  }

  return resend.emails.send({
    from: FROM_ADDRESS,
    to,
    subject: `Your RAMS: ${trade.task_name}`,
    text: `Attached is your CDM 2015 compliant RAMS for ${trade.task_name}. Generated by RAMS Forge.`,
    attachments: [
      {
        filename: `RAMS-${trade.slug}.pdf`,
        content: pdfBuffer,
      },
    ],
  });
}
