// Runs as a genuinely separate `node` process, invoked via child_process
// from lib/pdf.js — see the comment there for why. Reads a JSON job
// { trade, siteAddress } from stdin, writes raw PDF bytes to stdout.
// Nothing else may write to stdout: any diagnostics go to stderr.

import { createElement as h } from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const SLATE = "#2f3e47";
const ORANGE = "#f15a24";
const MUTED = "#5c6b74";
const BORDER = "#dfe3e6";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: "#151515", fontFamily: "Helvetica" },
  brand: { fontSize: 10, fontFamily: "Helvetica-Bold", color: SLATE, marginBottom: 4 },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", color: SLATE, marginBottom: 4 },
  meta: { fontSize: 9, color: MUTED, marginBottom: 20 },
  sectionTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: SLATE,
    marginTop: 18,
    marginBottom: 8,
    borderBottom: `1pt solid ${BORDER}`,
    paddingBottom: 4,
  },
  regRow: { flexDirection: "row", marginBottom: 3 },
  regBullet: { width: 10, color: ORANGE, fontFamily: "Helvetica-Bold" },
  regText: { flex: 1 },
  hazardBlock: { marginBottom: 10, paddingLeft: 10, borderLeft: `2pt solid ${ORANGE}` },
  hazardName: { fontSize: 10.5, fontFamily: "Helvetica-Bold", color: SLATE, marginBottom: 2 },
  hazardControl: { fontSize: 9.5, color: "#333" },
  ppeRow: { flexDirection: "row", flexWrap: "wrap" },
  ppeBadge: {
    fontSize: 9,
    color: SLATE,
    border: `1pt solid ${BORDER}`,
    borderRadius: 3,
    paddingVertical: 3,
    paddingHorizontal: 7,
    marginRight: 6,
    marginBottom: 6,
  },
  faqQ: { fontSize: 10, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  faqA: { fontSize: 9.5, color: "#333" },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    color: MUTED,
    borderTop: `1pt solid ${BORDER}`,
    paddingTop: 8,
  },
});

function buildRamsPdfElement(trade, siteAddress) {
  const generatedOn = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const regItems = trade.applicable_regs.map((reg) =>
    h(View, { style: styles.regRow, key: reg }, [
      h(Text, { style: styles.regBullet, key: "b" }, "—"),
      h(Text, { style: styles.regText, key: "t" }, reg),
    ])
  );

  const hazardBlocks = trade.hazards.map((hazard) =>
    h(View, { style: styles.hazardBlock, key: hazard.name }, [
      h(Text, { style: styles.hazardName, key: "n" }, hazard.name),
      h(Text, { style: styles.hazardControl, key: "c" }, `Control: ${hazard.control}`),
    ])
  );

  const ppeBadges = trade.required_ppe.map((ppe) =>
    h(Text, { style: styles.ppeBadge, key: ppe }, ppe)
  );

  return h(
    Document,
    { title: `RAMS - ${trade.task_name}` },
    h(
      Page,
      { size: "A4", style: styles.page },
      h(Text, { style: styles.brand }, "RAMS FORGE"),
      h(Text, { style: styles.title }, trade.h1_title),
      h(
        Text,
        { style: styles.meta },
        `${siteAddress ? `Site: ${siteAddress}  |  ` : ""}Generated: ${generatedOn}`
      ),

      h(Text, { style: styles.sectionTitle }, "Applicable Regulations"),
      ...regItems,

      h(Text, { style: styles.sectionTitle }, "Hazard & Risk Assessment"),
      ...hazardBlocks,

      h(Text, { style: styles.sectionTitle }, "Required PPE"),
      h(View, { style: styles.ppeRow }, ppeBadges),

      h(Text, { style: styles.sectionTitle }, "Frequently Asked Questions"),
      h(Text, { style: styles.faqQ }, trade.faq_q1),
      h(Text, { style: styles.faqA }, trade.faq_a1),

      h(
        Text,
        { style: styles.footer },
        "Generated by RAMS Forge (ramsforge.co.uk). This document is a site-specific starting point and should be reviewed by a competent person before use."
      )
    )
  );
}

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}

const input = JSON.parse(await readStdin());
const buf = await renderToBuffer(buildRamsPdfElement(input.trade, input.siteAddress));
process.stdout.write(buf);
